FROM debian

MAINTAINER Ltreu <ltreu@student.wethinkcode.co.za>

RUN apt-get update && apt-get upgrade -y && apt-get install -y apt-utils && apt-get install -y build-essential git

# How to build it?
# docker build -t a01 .

# How to run it?
# docker run --rm -ti a01