FROM ubuntu

MAINTAINER Ltreu <ltreu@student.wethinkcode.co.za>

RUN apt-get update && apt-get upgrade -y && apt-get install -y default-jdk default-jre git vim

# How to build it?
# docker build -t a03 .

# How to run it?
# docker run --rm -ti a03